version: "3.4"
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: licitacao
    working_dir: /licitacao
    image: php:alpine
    volumes:
      - "./:/licitacao"
    command: php artisan migrate 
    command: php artisan serve
    ports:
      - 8000:8000
    network_mode: host